ln -s ../images/tile_fabric.gif .
ln -s ../images/piglet.gif .
ln -s ../img_photos/ny_family* .
ln -s ../img_photos/pagoda_sm.jpg .
ln -s ../img_photos/night_club_* .
ln -s ../img_photos/night_scape_* .
ln -s ../img_photos/holocaust_??.??? .
ln -s ../img_photos/hatching_tn.gif .
ln -s ../img_photos/beijing_md.jpg .
ln -s ../img_photos/spiral_stairs_tn.gif .
ln -s ../img_photos/chinese_chess_tn.gif .
ln -s ../img_photos/anthony_*.jpg .
ln -s ../img_photos/jacob_vs_jacob_md.jpg .
ln -s ../img_photos/vegas_* .
ln -s ../img_photos/nikon* .
ln -s ../img_photos/zelda_tn.gif .
ln -s ../img_photos/taj_mahal_sm.png .
ln -s ../img_photos/shirt.jpg .
#ln -s ../images/night_sky.jpg .