ln -s ../images/koala.gif .
ln -s ../images/tree.gif .
ln -s ../images/logo.gif .
ln -s ../images/glitter_blue.gif .
ln -s ../images/rose.png .
ln -s ../images/grid16.png .
ln -s ../images/grid16_control_points.txt .
ln -s ../img_photos/building.jpg .
ln -s ../img_photos/lena_orig.png .
ln -s ../img_photos/mandrill_orig.png .
ln -s ../img_photos/mandrill_grid.jpg .
ln -s ../img_photos/pagoda_sm.jpg .
ln -s ../img_photos/barrel_distorted.jpg .
ln -s ../img_photos/worldmap_*.jpg .
ln -s ../img_photos/flower_sm.jpg .
ln -s ../img_photos/p90_* .
ln -s ../img_photos/mars_panorama_sm.jpg .
ln -s ../img_diagrams/cylinder2plane.png .
