ln -s ../images/rose.png .
ln -s ../images/rose_[fb]g_mask.png .
ln -s ../images/koala.gif .
ln -s ../images/knight.png .
ln -s ../images/cyclops.png .
ln -s ../images/moon.png .
ln -s ../images/tile_{disks,water,aqua}.jpg .
ln -s ../images/overlay_*.gif .
ln -s ../images/match_*.gif .
